# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 849e4038e7e97cec0ce1ceb24f4fcd41ea189f240841185a728a85dc03e0935e289936847c9643df4b45a8a6c776e5db7ffa67eca39b6584eb048780107e6526

test:
  secret_key_base: c68a815b0e06a2cf0c0bbe1cdb7d2d63ffded53591db0c9893f591aac732ade3b37369d6c8b6839f8da3012e6d2ee12f4a2cd5991de159958108321574590612

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
